### PR TITLE
Improve zip reading

### PR DESCRIPTION
**Pull request by artygus**
When parsing some epub files I'm getting

>  General purpose flag Bit 3 is set so not possible to get proper info from local header. Please use ::Zip::File instead of ::Zip::InputStream (Zip::GPFBit3Error)

This PR implements reading via `Zip::File` instead of `Zip::InputStream` that relies on metadata, more info can be found at https://github.com/rubyzip/rubyzip/tree/v2.3.2#notice-about-zipinputstream.

Test file `streamed_item.epub` was produced using the [new_book_example.rb](https://github.com/skoji/gepub/blob/049f5d7e0809d3d957f31fefb2961e2851eea85b/examples/new_book_example.rb) and adding empty file via `zip` command line tool to the epub with the `-fd` flag

```bash
touch empty.txt
zip -fd streamed_item.epub empty.txt
```

Fixes https://github.com/skoji/gepub/issues/135

### CODE REVIEW

**Review by skoji — APPROVED** [review]
👍

**Comment by slonopotamus** [comment]
This broke things downstream:

```
      RuntimeError:
        Zip::File.open_buffer expects a String or IO-like argument (responds to tell, seek, read, eof, close). Found: Pathname
      # ./vendor/bundle/ruby/3.3.0/gems/rubyzip-2.3.2/lib/zip/file.rb:145:in `open_buffer'
      # ./vendor/bundle/ruby/3.3.0/gems/gepub-1.0.16/lib/gepub/book.rb:105:in `parse'
      # ./spec/spec_helper.rb:83:in `to_epub'
      # ./spec/xref_spec.rb:46:in `block (2 levels) in <top (required)>'
```

Before this change, it was absolutely OK to pass `Pathname` to `GEPUB::Book.parse`. But now it doesn't work.

**Comment by artygus** [comment]
@slonopotamus it's because `Zip::InputStream::open` accepted either one or another. `Zip::File.open_buffer` is more consistent and accepts streams, as described in the doc to the method 

https://github.com/skoji/gepub/blob/c29a1bedecf9cc9646abb1b6d47c7eb2e9fd9666/lib/gepub/book.rb#L97-L100

it's up to @skoji to decide whether to maintain backwards compatibility, but it's worth mentioning method description never mention any input types except io.

**Comment by slonopotamus** [comment]
You know what. It looks like the issue only affects asciidoctor-epub3 test suite. The program itself was not broken. Let's leave everything as-is on gepub side.

**Comment by slonopotamus** [comment]
There is one more issue with this change, see https://github.com/skoji/gepub/issues/141.

**Pull request merged**
